name = "formalization"
version = "0.1.0"
defaultTargets = ["Formalization"]

[[lean_lib]]
name = "Formalization"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "master"